version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-1
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrongPassword123"
      MSSQL_PID: "Express"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - clac_common_network

volumes:
  mssql_data:

networks:
  clac_common_network:
    name: clac_common_network
    external: true
